import {zodResolver} from "@hookform/resolvers/zod";
import {loginInputSchema, registerInputSchema, type LoginInput, type RegisterInput} from "@skillbridge/shared";
import {useForm} from "react-hook-form";
import {Link, useNavigate} from "react-router-dom";
import {useLogin, useRegister} from "../hooks/auth";
import {errorMessage} from "../lib/api";
function Frame({title, subtitle, children, footer}: {title: string; subtitle: string; children: React.ReactNode; footer: React.ReactNode}) {return <div className="auth-page"><div className="auth-visual"><span className="eyebrow">SkillBridge AI</span><h1>Know what you have.<br/>Learn what you need.</h1><p>Turn your resume into an explainable career-readiness plan.</p></div><div className="auth-card"><h2>{title}</h2><p>{subtitle}</p>{children}<div className="auth-footer">{footer}</div></div></div>}
export function LoginPage() {const mutation = useLogin(); const navigate = useNavigate(); const form = useForm<LoginInput>({resolver: zodResolver(loginInputSchema), defaultValues: {email: "", password: ""}}); return <Frame title="Welcome back" subtitle="Sign in to continue." footer={<>New here? <Link to="/register">Create an account</Link></>}><form className="form-stack" onSubmit={form.handleSubmit((input) => mutation.mutate(input, {onSuccess: (data) => navigate(data.user.onboardingCompleted ? "/app/dashboard" : "/onboarding")}))}><label>Email<input type="email" {...form.register("email")}/><small>{form.formState.errors.email?.message}</small></label><label>Password<input type="password" {...form.register("password")}/><small>{form.formState.errors.password?.message}</small></label>{mutation.error && <div className="error-box">{errorMessage(mutation.error)}</div>}<button className="primary-button" disabled={mutation.isPending}>{mutation.isPending ? "Signing in…" : "Sign in"}</button></form></Frame>}
export function RegisterPage() {const mutation = useRegister(); const navigate = useNavigate(); const form = useForm<RegisterInput>({resolver: zodResolver(registerInputSchema), defaultValues: {fullName: "", email: "", password: ""}}); return <Frame title="Create your account" subtitle="Start with your profile, then analyse your resume." footer={<>Already registered? <Link to="/login">Sign in</Link></>}><form className="form-stack" onSubmit={form.handleSubmit((input) => mutation.mutate(input, {onSuccess: () => navigate("/onboarding")}))}><label>Full name<input {...form.register("fullName")}/><small>{form.formState.errors.fullName?.message}</small></label><label>Email<input type="email" {...form.register("email")}/><small>{form.formState.errors.email?.message}</small></label><label>Password<input type="password" {...form.register("password")}/><small>{form.formState.errors.password?.message}</small></label>{mutation.error && <div className="error-box">{errorMessage(mutation.error)}</div>}<button className="primary-button" disabled={mutation.isPending}>{mutation.isPending ? "Creating account…" : "Create account"}</button></form></Frame>}
